import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  // Files to exclude from Knip analysis
  // `src/components/ui` is generated by the Shadcn CLI: each component exports
  // its full public API whether or not this app uses every part of it
  ignore: ['src/libs/I18n.ts', 'src/types/I18n.ts', 'src/components/ui/**'],
  // Include custom Playwright test file suffixes
  playwright: {
    entry: ['tests/**/*.@(integ|e2e).ts'],
  },
  compilers: {
    css: (text: string) => [...text.matchAll(/(?<=@)import[^;]+/gu)].join('\n'),
  },
  treatConfigHintsAsErrors: true,
};

export default config;
